version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=drupal
    networks:
      - drupal-postgres

  drupal:
    image: drupal:latest
    networks:
      - drupal-postgres
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    ports:
      - 8080:80
    depends_on:
      - postgres

networks:
  drupal-postgres:

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
